language: rust
rust:
- stable
- nightly
jobs:
  allow_failures:
  - rust: nightly
  fast_finish: true
cache: cargo
script:
- cargo run -- tree-data/example.toml output
deploy:
  local_dir: output
  provider: pages:git
  skip_cleanup: true
  deploy_key: "deploy-key-skill-tree"
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_d7b9fac2d740_key -iv $encrypted_d7b9fac2d740_iv
  -in deploy-key-skill-tree.enc -out deploy-key-skill-tree -d
