[[group]]
name = "core"
items = [
  { name = "Future trait" },
  { name = "Async await" },
  { name = "Async fn in traits" },
  { name = "Core future combinators" },
  { name = "Async book" },
]

[[group]]
name = "runtime"
application = "Protocol servers and clients"
requires = [ "core" ]
items = [
  { name = "Files" },
  { name = "Timers" },
  { name = "Sockets" },
  { name = "Tasks" },
]

[[group]]
name = "web-basic"
application = "Basic web servers and clients"
requires = [ "runtime", "web protocols" ]
items = [
  { name = "Routing table" },
  { name = "Middleware" },
]

[[group]]
name = "web-advanced"
application = "Fully featured web servers and clients"
requires = [ "web-basic" ]
items = [
  { name = "Database drivers" },
  { name = "Web sockets" },
  { name = "Server sent events" },
  { name = "Isomorphic user interface" },
  { name = "Authentication middleware" },
]

[[group]]
name = "streams"
requires = [ "core" ]
items = [
  { name = "Generators and async generators" },
  { name = "Stream trait definition" },
]

[[group]]
name = "web protocols"
requires = [ "streams" ]
items = [
  { name = "HTTP 1.x" },
  { name = "HTTP 2.x" },
  { name = "QUIC / HTTP 3.x" },
  { name = "gRPC" },
  { name = "GRPC" },
]

[[group]]
name = "dev tooling"
requires = [ "core", "runtime" ]
items = [
  { name = "profiles" },
  { name = "logging" },
]
