[package]
name = "treeviz"
version = "0.1.0"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
rust-embed = "5.2.0"
structopt = "0.3.9"
serde = "1.0"
serde_derive = "1.0"
svg = "0.5.12"
toml = "0.5.1"
